version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: aleksup/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  frontend:
    image: aleksup/kittygram_frontend
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: nginx:1.25-alpine
    ports:
      - "9000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static
      - media_volume:/var/html/media
