version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: aleksup/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media

  frontend:
    image: aleksup/kittygram_frontend
    env_file: .env
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: aleksup/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - static_volume:/static
      - media_volume:/media
