version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    build: ./frontend/
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: nginx:1.25-alpine
    ports:
      - "9000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static
      - media:/var/html/media
