# Generated by Django 4.2.11 on 2024-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('name',)},
        ),
    ]
