# Generated by Django 4.2.11 on 2024-04-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_achievement_options_alter_cat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='achievements',
            new_name='achievement',
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.achievement'),
        ),
        migrations.AlterField(
            model_name='achievementcat',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cats.cat'),
        ),
    ]
